config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'reserves#index'
  resources :trains, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: '北海道' }, { id: 2, name: '青森県' }, { id: 3, name: '岩手県' },
    { id: 4, name: '宮城県' }, { id: 5, name: '秋田県' }, { id: 6, name: '山形県' },
    { id: 7, name: '福島県' }, { id: 8, name: '茨城県' }, { id: 9, name: '栃木県' },
    { id: 10, name: '群馬県' }, { id: 11, name: '埼玉県' }, { id: 12, name: '千葉県' },
    { id: 13, name: '東京都' }, { id: 14, name: '神奈川県' }, { id: 15, name: '新潟県' },
    { id: 16, name: '富山県' }, { id: 17, name: '石川県' }, { id: 18, name: '福井県' },
    { id: 19, name: '山梨県' }, { id: 20, name: '長野県' }, { id: 21, name: '岐阜県' },
    { id: 22, name: '静岡県' }, { id: 23, name: '愛知県' }, { id: 24, name: '三重県' },
    { id: 25, name: '滋賀県' }, { id: 26, name: '京都府' }, { id: 27, name: '大阪府' },
    { id: 28, name: '兵庫県' }, { id: 29, name: '奈良県' }, { id: 30, name: '和歌山県' },
    { id: 31, name: '鳥取県' }, { id: 32, name: '島根県' }, { id: 33, name: '岡山県' },
    { id: 34, name: '広島県' }, { id: 35, name: '山口県' }, { id: 36, name: '徳島県' },
    { id: 37, name: '香川県' }, { id: 38, name: '愛媛県' }, { id: 39, name: '高知県' },
    { id: 40, name: '福岡県' }, { id: 41, name: '佐賀県' }, { id: 42, name: '長崎県' },
    { id: 43, name: '熊本県' }, { id: 44, name: '大分県' }, { id: 45, name: '宮崎県' },
    { id: 46, name: '鹿児島県' }, { id: 47, name: '沖縄県' }
  ]
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :trains, through: :train_stations
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :stations, through: :train_stations
end

app/models/train_station.rb
class TrainStation < ApplicationRecord
  belongs_to :train
  belongs_to :station
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  

  # Active Hash
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  # Association

  # Validation
  with_options presence: true do
    validates :nickname
    validates :email
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/}
    validates :phone, format: { with: /\A\d{11}\z/}
    validates :postcode, format: { with: /\A\d{3}[-]\d{4}\z/}
    validates :prefecture_id, numericality: { other_than: 0}
    validates :city
    validates :address

    with_options format: { with: /\A[ぁ-んァ-ン一-龥々]+\z/} do
      validates :lastname
      validates :firstname
    end

    with_options format: {with: /\A[ァ-ヶー－]+\z/} do
      validates :lastname_kana
      validates :firstname_kana
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [
        :nickname, 
        :lastname,
        :firstname,
        :lastname_kana,
        :firstname_kana,
        :phone,
        :postcode,
        :prefecture_id,
        :city,
        :address,
        :building
        ]
      )
  end

  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
  #   end
  # end

end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController

  def index
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController

  def index
  end

  def new
    @train = Train.new
    @stations = Station.all
  end

  def create
    binding.pry
    Train.create(train_params)
  end

  private

  def train_params
    params.require(:train).permit(:name, :departure_date, :departure_time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reserves_helper.rb
module ReservesHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ReservedApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/reserves/index.html.haml
%h1 トップページ
%br
.login
  - if user_signed_in?
    = current_user.nickname
    %br
    = link_to destroy_user_session_path, method: :delete do
      ログアウト
    %br
    = link_to trains_path do
      列車を登録する
  - else
    = link_to new_user_registration_path do
      ユーザ新規登録
    %br
    = link_to new_user_session_path do
      ログイン

app/views/trains/create.html.haml
%h3 列車を登録しました
%br
= link_to trains_path do
  トップへ戻る

app/views/trains/index.html.haml
%h1 列車登録管理画面（管理者専用）
%br
.top
  = link_to "#" do
    列車一覧（準備中）
%br
.menu
  = link_to new_train_path do
    列車を登録する

app/views/trains/new.html.haml
%h1 列車登録画面
.form
  = form_with model: @train, local: true do |f|
    .trainname
      列車名
      = f.text_field :name
      %br
      始発駅出発日
      = f.date_select :departure_date, use_month_numbers: true
      %br
      始発駅出発時間
      = f.time_select :departure_time
      %br
      停車駅
      - @stations.each_with_index do |station, i|
        %br
        = f.check_box :station
        .stationname{data: {index: i}}
          = station.name
      %br
      = f.submit  "登録する"